// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrHF7qZasZfKix7exO1jMqXspGc8tVnZc',
    appId: '1:651863605412:web:ed34e7c41d10960e682631',
    messagingSenderId: '651863605412',
    projectId: 'biteboxx-dc20d',
    authDomain: 'biteboxx-dc20d.firebaseapp.com',
    storageBucket: 'biteboxx-dc20d.firebasestorage.app',
    measurementId: 'G-2WRJLDNYJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNUTuR4L1SVVaT6vy9Z6lW3gm3V63iO6k',
    appId: '1:651863605412:android:3cf54a39e823ef7b682631',
    messagingSenderId: '651863605412',
    projectId: 'biteboxx-dc20d',
    storageBucket: 'biteboxx-dc20d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpyH2qnwdW0h-p-tbTuXD2IAaaObzrSQw',
    appId: '1:651863605412:ios:ed542932b3449da5682631',
    messagingSenderId: '651863605412',
    projectId: 'biteboxx-dc20d',
    storageBucket: 'biteboxx-dc20d.firebasestorage.app',
    androidClientId: '651863605412-53j2b4ehb0l5kqf8n5gttr50dhcjmu9q.apps.googleusercontent.com',
    iosClientId: '651863605412-isgics249n4024snpsqe3eknt5kelv9g.apps.googleusercontent.com',
    iosBundleId: 'com.bitbox.user',
  );

}